baseURL = "/"
languageCode = "it"
title = "Lu.Na Cafè"
theme = "hugo-theme-ava"
paginate = 8
mainSections = "post"

[languages]
  [languages.en]
      languageName = "Italiano"

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true

[module]
  [module.hugoVersion]
    min = "0.87.0"
    
[params]
  ga_id=""
  mainSections = ["events"]
  disqus = "xxxxxxx"
  google_fonts = [
    ["Arizonia", "400"]
  ]

  [params.meta_tags]
    meta_description = "Ava is a light theme for your blog with essential features you might dig in."
    meta_og_title = "Hugo Ava Theme"
    meta_og_sitename = "Hugo Ava Theme"
    meta_og_type = "website"
    meta_og_url = "https://demos.julien-maury.dev/hugo-theme-ava"
    meta_og_image_ = "https://raw.githubusercontent.com/jmau111/hugo-theme-ava/main/images/default.jpeg"
    meta_og_image = "subheader.jpg"
    meta_og_description = "Ava is a light theme for your blog with essential features you might dig in."
    meta_twitter_card = "summary"
    meta_twitter_site = "@gohugoio"
    meta_twitter_creator = "@gohugoio"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        tabWidth = 4
        noClasses = false
        pygmentsUseClasses = true
        pygmentsCodefences = true

    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true   

    [markup.blackFriday]
        angledQuotes = true

[[menu.main]]
    name = "Menu"
    url = "/menu/"
    weight = 2

[[menu.main]]
    name = "Chi siamo"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Contattaci"
    url = "/contact/"
    weight = 3

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
