backend:
  name: git-gateway
  branch: main

# locale: "it"

media_folder: "site/static/images" # Folder where user uploaded files should go
public_folder: "/images"

collections: # A list of collections the CMS should be able to edit
  - name: "events" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Eventi" # Used in the UI, ie.: "New Post"
    folder: "site/content/events" # The path to the folder where the documents are stored
    filter:
      field: type
      value: event
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Intro Blurb", name: "description", widget: "text" }
      - { name: "type", default: "event", widget: "hidden" }
      - { name: "draft", default: false, widget: "hidden" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          sanitize_preview: "false",
        }
  - name: "menu" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Menu" # Used in the UI, ie.: "New Post"
    files:
      - label: "Menu"
        name: "menu"
        file: "site/data/menu.toml"
        format: "toml"
        fields:
          - label: Menu
            name: collection
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - { label: Sezione, name: name, widget: string }
              - { label: Immagine, name: image, widget: image }
              - { label: Valuta, name: currency, default: €, widget: string }
              - label: Prodotti
                name: items
                widget: list
                allow_add: true
                collapsed: false
                fields:
                  - { label: Nome prodotto, name: name, widget: string }
                  - { label: Prezzo, name: price, widget: string }
                  - {
                      label: Quantità,
                      name: unit,
                      required: false,
                      widget: string,
                    }
